<#
CoolSetup.ps1
A "very cool" PowerShell setup script with:
- A large simulated green loading bar (3.5 MB per 0.3s, max 2.1 GB)
- Pauses at completion with an OK dialog, then continues
- Creates an organized project folder with many example files
- Implements 25 friendly "features" described below
Run: Right-click -> Run with PowerShell, or from console:  powershell -ExecutionPolicy Bypass -File .\CoolSetup.ps1
#>

# -------------------------
# Feature list (25 things this script does)
# 1. Create root project folder
# 2. Create subfolders: bin, logs, configs, scripts, assets, docs, temp, installers
# 3. Generate README.md
# 4. Generate LICENSE (MIT stub)
# 5. Generate config.json (sample)
# 6. Generate .env file (sample)
# 7. Create sample PowerShell script (install-stub.ps1)
# 8. Create sample batch file (run.bat)
# 9. Create sample Python script (example.py)
# 10. Create sample HTML/CSS/JS assets (index.html, style.css, app.js)
# 11. Create a "loading_bar.bat" that echoes a message (small helper)
# 12. Create a app icon placeholder (icon.txt)
# 13. Create a CHANGELOG.md
# 14. Create a USER_MANUAL.md in docs
# 15. Create a log file and append startup entry
# 16. Create a scheduled-run stub file (task_stub.xml)
# 17. Create a sample JSON dataset (data.json)
# 18. Create an "examples" folder with 3 small example files
# 19. Create a desktop shortcut (.lnk) to the README (if possible)
# 20. Generate a random secure password and save to secrets.txt
# 21. Create a small "installer stub" script in installers
# 22. Output a pretty ASCII header & progress information
# 23. Provide a native OK message box when the simulated download completes
# 24. After OK, create final "installed" marker file and a summary report
# 25. Print a summary table of created files
# -------------------------

# -------------------------
# Configuration (change these if you want)
$ProjectRoot = Join-Path $env:USERPROFILE "CoolSetup_Project"
$SubFolders = @("bin","logs","configs","scripts","assets","docs","temp","installers","examples")
$ReadmePath = Join-Path $ProjectRoot "README.md"
$LogPath = Join-Path $ProjectRoot "logs\setup.log"
$MaxBytes = [int64](2.1 * 1024 * 1024 * 1024)        # 2.1 GB in bytes (exact float->int conversion)
$IncrementBytes = [int64](3.5 * 1024 * 1024)         # 3.5 MB in bytes
$TickDelaySeconds = 0.3                              # Pause per increment
$BarWidth = 50                                       # Progress bar width in characters
# -------------------------

# Helper: safe folder create
function Ensure-Folder {
    param([string]$Path)
    if (-not (Test-Path $Path)) {
        New-Item -ItemType Directory -Path $Path -Force | Out-Null
    }
}

# Ensure root and subfolders
Write-Host "`n[+] Creating project folders..." -ForegroundColor Cyan
Ensure-Folder -Path $ProjectRoot
foreach ($f in $SubFolders) {
    Ensure-Folder -Path (Join-Path $ProjectRoot $f)
}

# Create README.md
$readmeContent = @"
# CoolSetup Project

This project was generated by CoolSetup.ps1.
It contains example files, scripts, assets, and a simulated download + installer workflow.
"@
$readmeContent | Out-File -FilePath $ReadmePath -Encoding UTF8

# LICENSE (MIT)
$license = @"
MIT License

Copyright (c) $(Get-Date -Format yyyy) CoolSetup

Permission is hereby granted...
"@
$license | Out-File -FilePath (Join-Path $ProjectRoot "LICENSE.txt") -Encoding UTF8

# config.json
$configJson = @{
    name = "CoolSetup Project"
    version = "1.0.0"
    created = (Get-Date).ToString("s")
    settings = @{
        autoUpdate = $false
        verbose = $true
    }
}
$configJson | ConvertTo-Json -Depth 5 | Out-File -FilePath (Join-Path $ProjectRoot "configs\config.json") -Encoding UTF8

# .env
@"
# Sample .env
APP_NAME=CoolSetup
APP_ENV=development
MAX_DOWNLOAD_BYTES=$MaxBytes
"@ | Out-File -FilePath (Join-Path $ProjectRoot ".env") -Encoding UTF8

# Example scripts: PowerShell, batch, python
$psScript = @"
# install-stub.ps1
Write-Host 'This is a safe installer stub. It does not change system settings.'
Start-Sleep -Seconds 1
Write-Host 'Done stub.'
"@
$psScript | Out-File -FilePath (Join-Path $ProjectRoot "scripts\install-stub.ps1") -Encoding UTF8

$batScript = @"
@echo off
echo Running helper batch...
pause
"@
$batScript | Out-File -FilePath (Join-Path $ProjectRoot "scripts\loading_bar.bat") -Encoding ASCII

$pyScript = @"
# example.py
print('Hello from example.py')
"@
$pyScript | Out-File -FilePath (Join-Path $ProjectRoot "scripts\example.py") -Encoding UTF8

# web assets
@indexHtml = @"
<!doctype html>
<html>
<head><meta charset='utf-8'><title>CoolSetup Demo</title><link rel='stylesheet' href='style.css'></head>
<body><h1>CoolSetup Demo</h1><script src='app.js'></script></body>
</html>
"@
@indexHtml | Out-File -FilePath (Join-Path $ProjectRoot "assets\index.html") -Encoding UTF8

@"
body { font-family: Segoe UI, Arial; background: #111; color: #eee; padding: 1rem; }
"@ | Out-File -FilePath (Join-Path $ProjectRoot "assets\style.css") -Encoding UTF8

@"
console.log('CoolSetup asset loaded');
"@ | Out-File -FilePath (Join-Path $ProjectRoot "assets\app.js") -Encoding UTF8

# icon placeholder
"ICON_PLACEHOLDER" | Out-File -FilePath (Join-Path $ProjectRoot "assets\icon.txt") -Encoding UTF8

# CHANGELOG and USER_MANUAL
"## Changelog`n- 1.0.0 initial" | Out-File -FilePath (Join-Path $ProjectRoot "CHANGELOG.md") -Encoding UTF8
"User manual for CoolSetup. Follow steps to run." | Out-File -FilePath (Join-Path $ProjectRoot "docs\USER_MANUAL.md") -Encoding UTF8

# log startup
"$((Get-Date).ToString('s')) - Setup started" | Out-File -FilePath $LogPath -Encoding UTF8

# task_stub.xml
$taskXml = @"
<Task>
  <RegistrationInfo><Author>CoolSetup</Author></RegistrationInfo>
  <Triggers/>
  <Actions><Exec><Command>powershell.exe</Command><Arguments>-File `"$($ProjectRoot)\scripts\install-stub.ps1`"</Arguments></Exec></Actions>
</Task>
"@
$taskXml | Out-File -FilePath (Join-Path $ProjectRoot "task_stub.xml") -Encoding UTF8

# data.json
@(
    @{id=1; name="Alpha"; size=123},
    @{id=2; name="Beta"; size=456}
) | ConvertTo-Json | Out-File -FilePath (Join-Path $ProjectRoot "data.json") -Encoding UTF8

# examples (3 files)
"Example file 1" | Out-File -FilePath (Join-Path $ProjectRoot "examples\example1.txt")
"Example file 2" | Out-File -FilePath (Join-Path $ProjectRoot "examples\example2.txt")
"Example file 3" | Out-File -FilePath (Join-Path $ProjectRoot "examples\example3.txt")

# secrets (random password)
Add-Type -AssemblyName System.Security
$bytes = New-Object byte[] 32
[System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
$pw = [Convert]::ToBase64String($bytes)
"GeneratedPassword=$pw" | Out-File -FilePath (Join-Path $ProjectRoot "secrets.txt") -Encoding UTF8

# installer stub
@"
# installer-stub.txt
This is a safe installer stub. Replace with real installer content.
"@ | Out-File -FilePath (Join-Path $ProjectRoot "installers\installer-stub.txt") -Encoding UTF8

# mark created files array (will be filled more later)
$created = [System.Collections.Generic.List[string]]::new()
Get-ChildItem -Path $ProjectRoot -Recurse | ForEach-Object { $created.Add($_.FullName) }

# Function: draw progress bar in console, filled green for downloaded part
function Show-ProgressBar {
    param(
        [int64]$Downloaded,
        [int64]$Total,
        [int]$Width = 50
    )
    $percent = [math]::Min(100, [math]::Round( (100.0 * $Downloaded) / $Total , 2 ))
    $filledChars = [int]([math]::Floor(($percent/100.0) * $Width))
    $emptyChars = $Width - $filledChars

    # Build strings
    $filled = "#" * $filledChars
    $empty = "-" * $emptyChars

    # Write bar: color the filled part green
    # Clear current line
    $cursorLeft = [Console]::CursorLeft
    Write-Host -NoNewline ("`r[{0}{1}] {2}% - {3}/{4} MB" -f $filled, $empty, $percent, [math]::Round($Downloaded/1MB,2), [math]::Round($Total/1MB,2))

    # Repaint filled part in green by reconstructing output:
    # (Because Write-Host doesn't support mixed colors in a single call easily, we'll write in two parts)
    # Move cursor back to start of line and build pieces
    $barPrefix = "["
    $barSuffix = "] $percent% - {0}/{1} MB" -f [math]::Round($Downloaded/1MB,2), [math]::Round($Total/1MB,2)
    $toWrite = $barPrefix + $filled + $empty + $barSuffix

    # Use Console to control colors precisely
    $origFg = [Console]::ForegroundColor
    $origBg = [Console]::BackgroundColor

    # Write prefix
    [Console]::Write("`r" + $barPrefix)
    # Write filled green
    [Console]::ForegroundColor = "Green"
    [Console]::Write($filled)
    # Write empty
    [Console]::ForegroundColor = "DarkGray"
    [Console]::Write($empty)
    # Write suffix
    [Console]::ForegroundColor = $origFg
    [Console]::WriteLine($barSuffix)

    # Restore colors
    [Console]::ForegroundColor = $origFg
    [Console]::BackgroundColor = $origBg
}

# -------------------------
# Simulated download / loading bar
Write-Host "`n[+] Starting simulated download / setup transfer..." -ForegroundColor Cyan
$downloaded = 0
$iteration = 0
$totalIterations = [math]::Ceiling($MaxBytes / $IncrementBytes)

# Safety: cap iterations to avoid infinite loops
$maxAllowedIterations = 10000
if ($totalIterations -gt $maxAllowedIterations) {
    Write-Host "Iteration count is too large. Aborting." -ForegroundColor Red
    exit 1
}

while ($downloaded -lt $MaxBytes) {
    $iteration++
    $toAdd = [math]::Min($IncrementBytes, $MaxBytes - $downloaded)
    $downloaded += $toAdd

    # Show progress bar
    Show-ProgressBar -Downloaded $downloaded -Total $MaxBytes -Width $BarWidth

    # Append a little log every Nth iteration to file (not too often)
    if ($iteration % 50 -eq 0) {
        "$((Get-Date).ToString('s')) - simulated downloaded $([math]::Round($downloaded/1MB,2)) MB" | Out-File -FilePath $LogPath -Append -Encoding UTF8
    }

    Start-Sleep -Seconds $TickDelaySeconds
}

# Final ensure full bar shown
Show-ProgressBar -Downloaded $MaxBytes -Total $MaxBytes -Width $BarWidth

# -------------------------
# Native OK dialog: require user to click "OK" to continue.
# Use Windows Forms MessageBox for a native experience (works on Windows with .NET)
try {
    Add-Type -AssemblyName System.Windows.Forms -ErrorAction Stop
    $msg = "Download simulation complete.`nDownloaded {0} MB of {1} MB.`nClick OK to continue the setup." -f ([math]::Round($MaxBytes/1MB,2)), ([math]::Round($MaxBytes/1MB,2))
    [System.Windows.Forms.MessageBox]::Show($msg, "CoolSetup - Download Complete", [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Information) | Out-Null
}
catch {
    # If MessageBox fails (e.g., non-Windows or .NET issue), fallback to simple Read-Host
    Write-Host "`nDownload complete. Press Enter to continue..." -ForegroundColor Yellow
    Read-Host
}

# -------------------------
# After OK: create final "installed" marker and a summary report
$marker = Join-Path $ProjectRoot "INSTALL_COMPLETE.txt"
"Install completed at $((Get-Date).ToString('s'))" | Out-File -FilePath $marker -Encoding UTF8

# Append final log
"$((Get-Date).ToString('s')) - Setup finished successfully" | Out-File -FilePath $LogPath -Append -Encoding UTF8

# Attempt to create a desktop shortcut to README (best effort, no admin)
$desktop = [Environment]::GetFolderPath("Desktop")
$lnkPath = Join-Path $desktop "CoolSetup README.lnk"
try {
    $WshShell = New-Object -ComObject WScript.Shell
    $shortcut = $WshShell.CreateShortcut($lnkPath)
    $shortcut.TargetPath = $ReadmePath
    $shortcut.WorkingDirectory = $ProjectRoot
    $shortcut.WindowStyle = 1
    $shortcut.Description = "Open CoolSetup README"
    $shortcut.Save()
    $created.Add($lnkPath)
}
catch {
    # ignore failures (e.g., non-Windows)
}

# Re-scan created files
$created.Clear()
Get-ChildItem -Path $ProjectRoot -Recurse | ForEach-Object { $created.Add($_.FullName) }

# Build final summary content
$summary = @()
$summary += "CoolSetup Summary Report"
$summary += "Generated at: $((Get-Date).ToString('s'))"
$summary += ""
$summary += "Project root: $ProjectRoot"
$summary += ""
$summary += "Created entries (first 100 shown):"
$created | Select-Object -First 100 | ForEach-Object { $summary += ("- " + $_) }

# Write summary to file
$summaryPath = Join-Path $ProjectRoot "setup_summary.txt"
$summary | Out-File -FilePath $summaryPath -Encoding UTF8

# Print neat summary to console
Write-Host "`n========================================" -ForegroundColor Magenta
Write-Host "Setup complete! Created files summary (first 50):" -ForegroundColor Green
$created | Select-Object -First 50 | ForEach-Object { Write-Host $_ }
Write-Host "========================================" -ForegroundColor Magenta

# Open the README using default app (best effort)
try {
    Start-Process -FilePath $ReadmePath -WindowStyle Normal
}
catch { }

# Done
Write-Host "`nAll done. Enjoy your CoolSetup project!" -ForegroundColor Cyan
