<#
Ultimate_CHAOS_Setup.ps1
Description:
A long, chaotic PowerShell installer simulation that:
- Combines hacker-terminal style, Windows installer dialogs, game-like leveling, and chaos mode
- Simulates multiple phases with progress bars (multi-GB total simulated)
- Creates 50+ example files/folders, logs, installers, assets, and "loot"
- Shows Windows native dialogs, plays beeps, and prints ASCII animations
- Implements XP, levels, achievements, random chaos events, and a final "install complete" report

Usage:
powershell -ExecutionPolicy Bypass -File .\Ultimate_CHAOS_Setup.ps1

# Configurable values are near the top of the script.
# No admin rights required. No system settings changed.
# Enjoy responsibly.
#>

# -----------------------
# CONFIG
# -----------------------
$ProjectRoot = Join-Path $env:USERPROFILE "Ultimate_CHAOS_Project"
$SubFolders = @(
    "bin","logs","configs","scripts","assets","docs","temp","installers","examples",
    "loot","mods","patches","ui","levels","sounds","recipes","data","archives","cache"
)
$LogPath = Join-Path $ProjectRoot "logs\chaos_setup.log"
$SummaryPath = Join-Path $ProjectRoot "setup_summary.txt"
# Phase definitions: each phase has Name, SizeBytes, IncrementBytes, TickDelaySeconds, BarWidth
$Phases = @(
    @{Name="Phase 1 - Boot Sequence (Hacker)"; SizeGB=0.6; IncMB=4; Delay=0.25; Width=60},
    @{Name="Phase 2 - Installer Core (Windows)"; SizeGB=0.9; IncMB=5; Delay=0.28; Width=60},
    @{Name="Phase 3 - Game Assets (Loot & Models)"; SizeGB=1.2; IncMB=6; Delay=0.30; Width=60},
    @{Name="Phase 4 - Chaos Sync (Glitch)"; SizeGB=0.8; IncMB=3.5; Delay=0.22; Width=60},
    @{Name="Phase 5 - Finalizer & Patch (Wizard)"; SizeGB=0.5; IncMB=2.5; Delay=0.2; Width=60}
)
# Max iterations safety cap (total across phases)
$MaxAllowedIterations = 25000

# Game mechanics
$XPPerMB = 0.02        # XP earned per simulated MB
$LevelXPThreshold = 100  # XP needed to level (base, scaled)
$Achievements = [System.Collections.Generic.List[string]]::new()

# Random/chaos seed
$rand = New-Object System.Random

# -----------------------
# Helpers
# -----------------------
function Ensure-Folder { param([string]$Path) if (-not (Test-Path $Path)) { New-Item -ItemType Directory -Path $Path -Force | Out-Null } }
function Log { param([string]$Line) $t = (Get-Date).ToString('s'); "$t`t$Line" | Out-File -FilePath $LogPath -Append -Encoding UTF8 }
function SafeWrite { param([string]$Text, [ConsoleColor]$Color = "Gray") $orig = [Console]::ForegroundColor; [Console]::ForegroundColor = $Color; Write-Host $Text; [Console]::ForegroundColor = $orig }

# Create project structure
Write-Host "`n[+] Creating Ultimate CHAOS project folders..." -ForegroundColor Cyan
Ensure-Folder -Path $ProjectRoot
foreach ($s in $SubFolders) { Ensure-Folder -Path (Join-Path $ProjectRoot $s) }

# Seed initial files
"Ultimate CHAOS Setup started at $((Get-Date).ToString('s'))" | Out-File -FilePath $LogPath -Encoding UTF8
# README
@"
# Ultimate_CHAOS_Project

Generated by Ultimate_CHAOS_Setup.ps1
This folder contains simulated installer output, loot, mods, and demo assets.
"@ | Out-File -FilePath (Join-Path $ProjectRoot "README.md") -Encoding UTF8

# Small helper: create many example files with random content
function Create-RandomFile {
    param([string]$Path, [int]$SizeKB=4)
    $bytes = New-Object Byte[] ($SizeKB * 1024)
    [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    [IO.File]::WriteAllBytes($Path, $bytes)
}

# Create 50+ files across folders
$createdFiles = [System.Collections.Generic.List[string]]::new()
for ($i=1; $i -le 60; $i++) {
    $folder = (Join-Path $ProjectRoot $SubFolders[$i % $SubFolders.Count])
    $fname = "file_$([string]::Format("{0:000}", $i))_$(Get-Random -Maximum 9999).bin"
    $path = Join-Path $folder $fname
    Create-RandomFile -Path $path -SizeKB (Get-Random -Minimum 1 -Maximum 20)
    $createdFiles.Add($path)
}
# Create human-readable extras
$notes = @(
    "INSTALL_NOTES.txt","LICENSE.txt","CHANGELOG.md","USER_MANUAL.md","HINTS_AND_TIPS.txt"
)
foreach ($n in $notes) {
    $p = Join-Path $ProjectRoot $n
    "This is $n generated by Ultimate_CHAOS_Setup." | Out-File -FilePath $p -Encoding UTF8
    $createdFiles.Add($p)
}

Log "Initial file generation complete. Files created: $($createdFiles.Count)"

# -----------------------
# UI Helpers: ASCII and animations
# -----------------------
function Clear-Line { Write-Host -NoNewline "`r" + (" " * ([Console]::WindowWidth - 1)) + "`r" }
function Spinner-Animation {
    param([int]$DurationMs=1200)
    $icons = @('|','/','-','\')
    $start = Get-Date
    while ((Get-Date) - $start).TotalMilliseconds -lt $DurationMs {
        foreach ($ic in $icons) {
            Write-Host -NoNewline "$ic`r"
            Start-Sleep -Milliseconds 80
        }
    }
    Clear-Line
}

# Show hacker header
function Show-HackerHeader {
    Clear-Host
    SafeWrite "╔════════════════════════════════════════════════════════════════╗" Green
    SafeWrite "║    ULTIMATE  —  CHAOS  SETUP  —  HACKER-TERMINAL + WIZARD UI    ║" Green
    SafeWrite "╚════════════════════════════════════════════════════════════════╝" Green
    Write-Host ""
    SafeWrite "Booting virtual modules..." Gray
    Spinner-Animation -DurationMs 800
}

# -----------------------
# Progress bar function with colored filled part
# -----------------------
function Show-ProgressBar {
    param(
        [int64]$Downloaded,
        [int64]$Total,
        [int]$Width = 50,
        [string]$Prefix = ""
    )
    $percent = [math]::Min(100, [math]::Round( (100.0 * $Downloaded) / $Total , 2 ))
    $filledChars = [int]([math]::Floor(($percent/100.0) * $Width))
    $emptyChars = $Width - $filledChars
    $filled = "█" * $filledChars
    $empty = " " * $emptyChars
    $mbDownloaded = [math]::Round($Downloaded / 1MB, 2)
    $mbTotal = [math]::Round($Total / 1MB, 2)
    $line = "{0}[{1}{2}] {3}% - {4}/{5} MB" -f $Prefix, $filled, $empty, $percent, $mbDownloaded, $mbTotal
    # For color, write prefix+filled green, empty in dark gray, suffix normal
    [Console]::Write("`r")
    [Console]::ForegroundColor = "DarkCyan"
    [Console]::Write($Prefix + "[")
    [Console]::ForegroundColor = "Green"
    [Console]::Write($filled)
    [Console]::ForegroundColor = "DarkGray"
    [Console]::Write($empty)
    [Console]::ForegroundColor = "DarkCyan"
    [Console]::Write("] ")
    [Console]::ForegroundColor = "Yellow"
    [Console]::Write("{0}% - {1}/{2} MB" -f $percent, $mbDownloaded, $mbTotal)
    [Console]::ForegroundColor = "Gray"
}

# -----------------------
# MessageBox helper
# -----------------------
function Show-OKBox {
    param([string]$Text, [string]$Title = "Ultimate CHAOS")
    try {
        Add-Type -AssemblyName System.Windows.Forms -ErrorAction Stop
        [System.Windows.Forms.MessageBox]::Show($Text, $Title, [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Information) | Out-Null
    } catch {
        Write-Host "`n$Text"
        Read-Host "Press Enter to continue..."
    }
}

# -----------------------
# Game: XP / Level functions
# -----------------------
$XP = 0.0
$Level = 1
function Add-XP {
    param([double]$amount)
    $global:XP += $amount
    # simple level scaling: each level needs Level * LevelXPThreshold XP
    $threshold = $global:Level * $LevelXPThreshold
    while ($global:XP -ge $threshold) {
        $global:XP -= $threshold
        $global:Level += 1
        $threshold = $global:Level * $LevelXPThreshold
        $ach = "Leveled to $($global:Level) at $((Get-Date).ToString('s'))"
        $Achievements.Add($ach)
        Log $ach
        # celebratory beep and message
        [Console]::Beep(800,120)
        SafeWrite ">>> ACHIEVEMENT: LEVEL UP! You are now Level $($global:Level) <<<" Cyan
    }
}

# -----------------------
# Chaos Event: creates many small temp files randomly
# -----------------------
function Chaos-Event {
    param([int]$Intensity = 12)
    SafeWrite "`n*** CHAOS EVENT! Creating $Intensity temporary artifacts... ***`n" Magenta
    for ($i=1; $i -le $Intensity; $i++) {
        $p = Join-Path $ProjectRoot ("temp\chaos_" + (Get-Random -Minimum 100000 -Maximum 999999) + ".tmp")
        try {
            Create-RandomFile -Path $p -SizeKB (Get-Random -Minimum 1 -Maximum 10)
            $createdFiles.Add($p)
        } catch { }
        Start-Sleep -Milliseconds (Get-Random -Minimum 20 -Maximum 120)
    }
    Log "Chaos event created $Intensity temp files."
}

# -----------------------
# Phase Runner: runs each phase, returns total iterations used
# -----------------------
function Run-Phase {
    param([hashtable]$phase)
    $name = $phase.Name
    $sizeBytes = [int64]([math]::Round($phase.SizeGB * 1024 * 1024 * 1024))
    $incBytes = [int64]([math]::Round($phase.IncMB * 1024 * 1024))
    $delay = [double]$phase.Delay
    $width = [int]$phase.Width

    SafeWrite "`n--- $name ---" Yellow
    Log "Starting $name (SizeGB=$($phase.SizeGB), IncMB=$($phase.IncMB), Delay=$delay)"
    $downloaded = 0
    $iteration = 0
    $totalIterationsForPhase = [math]::Ceiling($sizeBytes / $incBytes)

    # Safety
    if ($totalIterationsForPhase -gt $MaxAllowedIterations) {
        SafeWrite "Phase iterations exceed allowed cap. Reducing increments to keep safe." Red
        $incBytes = [math]::Ceiling($sizeBytes / $MaxAllowedIterations)
        $totalIterationsForPhase = [math]::Ceiling($sizeBytes / $incBytes)
    }

    while ($downloaded -lt $sizeBytes) {
        $iteration++
        $toAdd = [math]::Min($incBytes, $sizeBytes - $downloaded)
        $downloaded += $toAdd

        # show progress
        Show-ProgressBar -Downloaded $downloaded -Total $sizeBytes -Width $width -Prefix ("{0} " -f $name.Substring(0, [math]::Min(12,$name.Length)))

        # random micro events
        if (($iteration % ([math]::Max(1, [int](($totalIterationsForPhase / 8))))) -eq 0) {
            # give XP
            $mb = ($toAdd / 1MB)
            $xpGain = [math]::Round($mb * $XPPerMB * (1 + ($rand.NextDouble() * 0.6)),2)
            Add-XP -amount $xpGain
            Log ("$name: +$xpGain XP (iter $iteration)")
            # small chance of chaos event
            if ($rand.Next(0,100) -lt 18) { Chaos-Event -Intensity (Get-Random -Minimum 6 -Maximum 18) }
        }

        # small chance of "glitch" visual
        if ($rand.Next(0,100) -lt 6) {
            $glitch = ("[G]" * (Get-Random -Minimum 1 -Maximum 6))
            Write-Host "`r$glitch" -ForegroundColor DarkRed -NoNewline
            Start-Sleep -Milliseconds (Get-Random -Minimum 60 -Maximum 220)
        }

        Start-Sleep -Seconds $delay
    }

    # ensure full bar
    Show-ProgressBar -Downloaded $sizeBytes -Total $sizeBytes -Width $width -Prefix ("{0} " -f $name.Substring(0, [math]::Min(12,$name.Length)))
    Write-Host ""
    SafeWrite ">>> $name complete." DarkGreen
    [Console]::Beep(600,90)
    return $iteration
}

# -----------------------
# Main sequence
# -----------------------
Show-HackerHeader
SafeWrite "Initializing multi-phase chaos installer..." Cyan
Start-Sleep -Milliseconds 600
Log "Multi-phase installer started."

$totalIterationsUsed = 0
foreach ($ph in $Phases) {
    $iters = Run-Phase -phase $ph
    $totalIterationsUsed += $iters
    if ($totalIterationsUsed -gt $MaxAllowedIterations) {
        SafeWrite "Total iterations exceeded safe cap. Aborting extra phases." Red
        break
    }
    # after some phases, show a Windows-style dialog
    if ($rand.Next(0,100) -lt 65) {
        $txt = "$($ph.Name)`nPhase complete.`nClick OK to continue to the next phase."
        Show-OKBox -Text $txt -Title "Ultimate CHAOS - Phase Complete"
    }
}

# Randomly generate some "mods", "patches" and "loot" files
function Create-Loot {
    $lootNames = @("Obsidian_Shard","Quantum_Core","Neon_Circuit","LuckyCharm","Beta_Patch")
    for ($i=0; $i -lt 16; $i++) {
        $name = $lootNames[$i % $lootNames.Count] + "_" + (Get-Random -Minimum 1000 -Maximum 99999) + ".loot"
        $path = Join-Path $ProjectRoot ("loot\" + $name)
        Create-RandomFile -Path $path -SizeKB (Get-Random -Minimum 2 -Maximum 48)
        $createdFiles.Add($path)
    }
    Log "Created loot files."
}
Create-Loot

# Create special "level" files and JSON descriptors
for ($lvl=1; $lvl -le 12; $lvl++) {
    $desc = @{
        level = $lvl
        xpRequired = $lvl * $LevelXPThreshold
        reward = "Reward_$($lvl)"
    }
    $desc | ConvertTo-Json | Out-File -FilePath (Join-Path $ProjectRoot ("levels\level_" + $lvl + ".json")) -Encoding UTF8
    $createdFiles.Add(Join-Path $ProjectRoot ("levels\level_" + $lvl + ".json"))
}

# Simulated installer wizard UI (console emphasis)
SafeWrite "`n[ Installer Wizard ]" Cyan
Write-Host "Steps:"
Write-Host " 1) Validate virtual signature"
Write-Host " 2) Extract assets"
Write-Host " 3) Apply patches"
Write-Host " 4) Finalize"
Spinner-Animation -DurationMs 900

# Simulate validation with beep patterns
SafeWrite "Validating virtual signature..." Gray
for ($i=0; $i -lt 6; $i++) { [Console]::Beep((Get-Random -Minimum 600 -Maximum 1100), 60); Start-Sleep -Milliseconds 80 }
SafeWrite "Signature OK." Green
Log "Signature validation simulated."

# Random "correction" / patch event
if ($rand.Next(0,100) -lt 40) {
    SafeWrite "`nApplying emergency micro-patch..." Yellow
    Chaos-Event -Intensity (Get-Random -Minimum 4 -Maximum 12)
    SafeWrite "Micro-patch applied." Green
}

# Reward the user XP for completing phases
$bonusXP = [math]::Round(($totalIterationsUsed % 100) * 0.5 + (Get-Random -Minimum 12 -Maximum 48),2)
Add-XP -amount $bonusXP
Log "Bonus XP granted: $bonusXP"

# Achievement check
if ($Level -ge 3) { $Achievements.Add("Rising Hacker - Reached level $Level") }
if ($createdFiles.Count -ge 80) { $Achievements.Add("Artifact Hoarder - Created $($createdFiles.Count) files") }

# Show final native dialog asking to continue to finalize install
Show-OKBox -Text "All phases complete.`nXP: $([math]::Round($XP,2))`nLevel: $Level`nClick OK to finalize and generate final report." -Title "Ultimate CHAOS - Finalize"

# Finalize: create INSTALL_COMPLETE marker + report
$marker = Join-Path $ProjectRoot "INSTALL_COMPLETE.txt"
"Install completed at $((Get-Date).ToString('s')) — Level $Level — XP $([math]::Round($XP,2))" | Out-File -FilePath $marker -Encoding UTF8
$createdFiles.Add($marker)

# Summary file
$summary = @()
$summary += "Ultimate_CHAOS Setup Summary"
$summary += "Generated at: $((Get-Date).ToString('s'))"
$summary += ""
$summary += "Project root: $ProjectRoot"
$summary += ""
$summary += "Total created files: $($createdFiles.Count)"
$summary += ""
$summary += "Top achievements:"
if ($Achievements.Count -gt 0) {
    foreach ($a in $Achievements) { $summary += (" - " + $a) }
} else {
    $summary += " - None"
}
$summary += ""
$summary += "First 200 created files:"
$createdFiles | Select-Object -First 200 | ForEach-Object { $summary += (" - " + $_) }

$summary | Out-File -FilePath $SummaryPath -Encoding UTF8
Log "Summary generated."

# Try to create Desktop shortcut to README (best-effort)
try {
    $desktop = [Environment]::GetFolderPath("Desktop")
    $lnk = Join-Path $desktop "Ultimate_CHAOS README.lnk"
    $Wsh = New-Object -ComObject WScript.Shell
    $shortcut = $Wsh.CreateShortcut($lnk)
    $shortcut.TargetPath = (Join-Path $ProjectRoot "README.md")
    $shortcut.WorkingDirectory = $ProjectRoot
    $shortcut.Description = "Ultimate CHAOS README"
    $shortcut.Save()
    $createdFiles.Add($lnk)
} catch { Log "Shortcut creation failed: $_" }

# Final fanfare: ASCII confetti + beep sequence
function Confetti-And-Fanfare {
    SafeWrite "`n" Cyan
    $colors = [enum]::GetValues([ConsoleColor])
    for ($r=0; $r -lt 9; $r++) {
        $line = ""
        for ($c=0; $c -lt ([Console]::WindowWidth / 2); $c++) {
            $ch = @('@','#','$','%','*','+','~','!')[Get-Random -Minimum 0 -Maximum 7]
            $line += $ch
        }
        [Console]::ForegroundColor = $colors[(Get-Random -Minimum 2 -Maximum ($colors.Length -1))]
        Write-Host $line
        Start-Sleep -Milliseconds 90
    }
    [Console]::ForegroundColor = "Gray"
    # Beep melody
    $melody = @(440, 523, 659, 880)
    foreach ($n in $melody) { [Console]::Beep($n, 80); Start-Sleep -Milliseconds 60 }
}
Confetti-And-Fanfare

# Open the summary and README (best-effort)
try { Start-Process -FilePath $SummaryPath } catch {}
try { Start-Process -FilePath (Join-Path $ProjectRoot "README.md") } catch {}

# Final console summary
SafeWrite "`n========================================" Magenta
SafeWrite "ULTIMATE CHAOS SETUP COMPLETE!" Green
Write-Host "Project root: $ProjectRoot"
Write-Host "Files created: $($createdFiles.Count)"
Write-Host "Level: $Level  XP: $([math]::Round($XP,2))"
Write-Host "Achievements: $($Achievements.Count)"
SafeWrite "========================================`n" Magenta

Log "Ultimate CHAOS Setup finished. Files created: $($createdFiles.Count). Level: $Level XP: $([math]::Round($XP,2))."

# End
Show-OKBox -Text "Ultimate CHAOS setup finished successfully.`nVisit $ProjectRoot to view files." -Title "Ultimate CHAOS - Done"
Write-Host "`nAll done — enjoy your chaos! 😈" -ForegroundColor Cyan
