# ============================================
# 🌟 Lorry Ultra Toolkit - PowerShell Edition 🌟
# ============================================

# --- COLOR SETUP ---
$Host.UI.RawUI.ForegroundColor = "Cyan"
Clear-Host

function Show-Title {
    param([string]$text)
    Clear-Host
    Write-Host "============================================" -ForegroundColor Yellow
    Write-Host "     🌟  $text  🌟" -ForegroundColor Cyan
    Write-Host "============================================" -ForegroundColor Yellow
    Write-Host ""
}

# --- ANIMATION ---
function Loading-Bar {
    param([int]$speed = 50)
    $bar = ""
    for ($i = 0; $i -le 30; $i++) {
        $bar += "█"
        Write-Host "`rLoading: $bar" -NoNewline
        Start-Sleep -Milliseconds $speed
    }
    Write-Host "`nDone!"
    Start-Sleep -Seconds 1
}

# --- FAKE VIRUS SCAN ---
function Fake-Scan {
    Show-Title "Lorry Ultra Scanner"
    $items = @(
        "Scanning Boot Sector...",
        "Checking System32...",
        "Analyzing Memory...",
        "Verifying Drivers...",
        "Inspecting Registry...",
        "Checking Temp Files...",
        "Scanning Network Ports...",
        "Analyzing User Profiles..."
    )

    foreach ($item in $items) {
        Write-Host "$item" -ForegroundColor Green
        Loading-Bar -speed (Get-Random -Minimum 40 -Maximum 120)
    }

    Write-Host "`n✅ No threats found!" -ForegroundColor Cyan
    Pause
}

# --- SYSTEM INFO ---
function System-Info {
    Show-Title "System Information Panel"

    Write-Host "🔧 PC Name: $env:COMPUTERNAME"
    Write-Host "👤 User: $env:USERNAME"
    Write-Host "🖥️ OS: $((Get-CimInstance Win32_OperatingSystem).Caption)"
    Write-Host "💾 RAM: $([math]::Round((Get-CimInstance Win32_PhysicalMemory | Measure-Object -Property Capacity -Sum).Sum / 1GB,2)) GB"
    Write-Host "⚡ CPU: $((Get-CimInstance Win32_Processor).Name)"
    Write-Host "⏳ Uptime: $((Get-CimInstance Win32_OperatingSystem).LastBootUpTime)"

    Write-Host "`nPress any key to return..."
    $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
}

# --- FILE MAKER ---
function Create-Files {
    Show-Title "File Generator"

    $path = "$env:USERPROFILE\Desktop\LorryFiles"
    if (!(Test-Path $path)) { New-Item -ItemType Directory -Path $path | Out-Null }

    for ($i = 1; $i -le 25; $i++) {
        $filename = "$path\File_$i.txt"
        Set-Content -Path $filename -Value "Generated by Lorry Ultra Toolkit (#$i)"
        Write-Host "Created: $filename" -ForegroundColor Green
        Start-Sleep -Milliseconds 80
    }

    Write-Host "`n📁 Files created on Desktop\LorryFiles!" -ForegroundColor Cyan
    Pause
}

# --- FAKE HACKER MODE ---
function Hacker-Mode {
    Show-Title "Hacker Console"

    for ($i = 1; $i -le 100; $i++) {
        $rand = -join ((65..90) + (48..57) | Get-Random -Count 40 | % {[char]$_})
        Write-Host $rand -ForegroundColor Green
        Start-Sleep -Milliseconds 40
    }

    Write-Host "`n💻 Hacker Console Complete." -ForegroundColor Yellow
    Pause
}

# --- MENU SYSTEM ---
function Main-Menu {
    while ($true) {
        Show-Title "Lorry Ultra Toolkit"

        Write-Host "1) 🛡️ Run Fake Virus Scan"
        Write-Host "2) 🧩 System Information"
        Write-Host "3) 📁 Create 25 Files"
        Write-Host "4) 💻 Hacker Console"
        Write-Host "5) 🔄 Restart Script"
        Write-Host "0) ❌ Exit"
        Write-Host ""
        $choice = Read-Host "Enter choice"

        switch ($choice) {
            "1" { Fake-Scan }
            "2" { System-Info }
            "3" { Create-Files }
            "4" { Hacker-Mode }
            "5" { & $PSCommandPath }
            "0" { exit }
            default {
                Write-Host "❌ Invalid option!" -ForegroundColor Red
                Start-Sleep 1
            }
        }
    }
}

# --- STARTUP ---
Show-Title "Starting Lorry Ultra Toolkit"
Loading-Bar -speed 5
Main-Menu
